services:
  - type: web
    name: face-recognition-app
    env: python
    plan: free
    buildCommand: pip install -r requirements_deploy.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 10000
